[package]
name = "ban-apis"
version = "0.1.0"
authors = ["Joseph Malicki <joseph@example.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
dylint_linting = "0.1.0"

[dev-dependencies]
dylint_testing = "0.1.0"
